version: '3.3'

services:
  frontend: 
    image: node:alpine
    container_name: portfolio.biancardi
    ports:
      - 4000:4000
    working_dir: /var/www/portfolio.biancardi
    volumes:
      - .:/var/www/portfolio.biancardi
    networks:
      - portfolio_network
    tty: true
    command: sh ./run.sh

networks:
  portfolio_network:
    driver: bridge